services:
  api:
    # build: .
    image: ghcr.io/sreekeerthi38/mlops-catsdogs:latest
    container_name: catsdogs-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.pt
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: catsdogs-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
    restart: unless-stopped